#!/usr/bin/env bash

JOURNAL_MARIADB="${JOURNAL_MARIADB:=mariadb}"
JOURNAL_AUDIT="${JOURNAL_AUDIT:=mysql-server_auditing}"
BACKUP_DATE="${BACKUP_DATE:=$(date +'%d%m%Y-%H%M%S')}"
BACKUP_DIR="${BACKUP_DIR:=/mnt/backups}"
BACKUP_NAME="bkp-mariadb-${BACKUP_DATE}"
BACKUP_PATH="${BACKUP_DIR}/${BACKUP_NAME}"
BACKUP_COMPRESSOR="${BACKUP_COMPRESSOR:=gzip}"
BACKUP_EXT="${BACKUP_EXT:=sql.gz}"

BACKUP_DUMP_FILE="${BACKUP_DIR}/${BACKUP_DATE}/${BACKUP_NAME}.${BACKUP_EXT}"

DUMP_OPTS="${DUMP_OPTS:=--all-databases --single-transaction --master-data=2 --routines --triggers --events}"

stop_slave() {
    mariadb --show-warnings -NBe "STOP SLAVE"
}

start() {
    systemctl start mariadb
}


stop() {
    systemctl stop mariadb
}

status() {
    systemctl status mariadb
}

slave() {
    mariadb -E -e "show slave status"
}

master() {
    mariadb -e "show master status"
}

slaves() {
    mariadb -e "show slave hosts"
}

errors() {
    journalctl -u ${JOURNAL_MARIADB} -xe
}

audit() {
    journalctl -u ${JOURNAL_MARIADB} -xe
}

backup() {
    mariadb-backup --backup --target-dir
}

restore() {
    mariadb-backup --prepare 
}

dump() {
    mariadb-dump ${DUMP_OPTS} | ${BACKUP_COMPRESSOR} > ${BACKUP_DUMP_FILE}
}

help() {
    exit 0
}


case "${1}" in
    stop)
        stop
        ;;
    start)
        start
        ;;
    status)
        status
        ;;
    backup)
        backup
        ;;
    dump)
        dump
        ;;
    *)
       print_usage 
        ;;
esac

exit 0
