#!/usr/bin/env bash

JOURNAL_MARIADB="${JOURNAL_MARIADB:=mariadb}"
JOURNAL_AUDIT="${JOURNAL_AUDIT:=mysql-server_auditing}"

BACKUP_ROOT="${BACKUP_ROOT:=/glide/mysql/backup}"
BACKUP_DATE="${BACKUP_DATE:=$(date +'%d%m%Y-%H%M%S')}"
DUMP_OPTS="${DUMP_OPTS:=--quick --all-databases --quick --single-transaction --master-data=2 --routines --triggers --events}"
DUMP_NAME="${DUMP_NAME:=dump-${BACKUP_DATE}.gz}"
DUMP_FILE="${DUMP_FILE:=${BACKUP_ROOT}/${DUMP_NAME}}"


stop_slave() {
    mariadb --show-warnings -NBe "STOP SLAVE"
}

start_slave() {
    mariadb --show-warnings -NBe "START SLAVE"
}

start() {
    systemctl start mariadb
}

restart() {
    systemctl restart mariadb
}

stop() {
    systemctl stop mariadb
}

status() {
    systemctl status mariadb
}

set_read_only() {
    mariadb -NBe "SET GLOBAL read_only=1"
}

set_write() {
    mariadb -NBe "SET GLOBAL read_only=0"
}

slave_status() {
    mariadb -E -e "show slave status"
}

master_status() {
    mariadb -e "show master status"
}

show-slaves() {
    mariadb -e "show slave hosts"
}

error_log() {
    journalctl -u ${JOURNAL_MARIADB} -xe
}

audit_log() {
    journalctl -u ${JOURNAL_MARIADB} -xe
}

backup() {
    full-bkp.sh
}

dump() {
    mariadb-dump ${DUMP_OPTS} | gzip > ${DUMP_FILE}
}

print_usage() {
    echo "Available commands:"
    declare -F | sed 's/_/-/g' | cut -d" " -f 3
    exit 0
}


case "${1}" in
    stop)
        stop
        ;;
    start)
        start
        ;;
    restart)
        restart
        ;;
    status)
        status
        ;;
    slave-status)
       slave_status
        ;;
    start-slave)
       start_slave 
        ;;
    stop-slave)
       stop_slave 
        ;;
    master-status)
      master_status 
        ;;
    backup)
        backup
        ;;
    dump)
        dump
        ;;
    audit-log)
       audit_log 
        ;;
    error-log)
       error_log 
        ;;
    set-read-only)
       set_read_only
        ;;
    set-write)
       set_write
        ;;
    help)
       print_usage 
        ;;
    "-h")
       print_usage 
        ;;
    "--help")
       print_usage 
        ;;
    *)
       echo "No command specificied"
       exit 0
        ;;
esac

exit 0
