$setup= <<-SETUP
dnf install -yq epel-release
dnf update -yq
dnf upgrade -yq
dnf install -yq vim python3-PyMySQL jq tmux curl wget mariadb-client
SETUP

$install_mariadb= <<-INSTALL_MARIADB
dnf install -yq mariadb-server mariadb-backup && \
    systemctl enable mariadb && \
    systemctl restart mariadb && \
    mariadb < /vagrant/setup.sql
INSTALL_MARIADB

$install_maxscale= <<-INSTALL_MAXSCALE
INSTALL_MAXSCALE


Vagrant.configure("2") do |config|
  config.vm.box = "generic/rocky9"

  1.upto(4) do |i|
      config.vm.define "db#{i}" do |node|
        node.vm.hostname = "db#{i}"
        node.vm.network "private_network", ip:"192.168.51.1#{i}"
        node.vm.provision "shell", inline: $setup
        node.vm.provision "shell", inline: $install_mariadb
    end
  end

  config.vm.define "mxs", primary: true do |m|
    m.vm.hostname = "mxs"
    m.vm.network "private_network", ip:"192.168.50.10"
    m.vm.provision "shell", inline: $setup
    m.vm.provision "shell", inline: $install_maxscale
  end

end
